# Generated by Django 4.1.2 on 2022-10-22 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='theanh',
        ),
    ]
