# Generated by Django 4.1.2 on 2022-10-22 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_book_theanh'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='locallibray/files/covers'),
            preserve_default=False,
        ),
    ]
